### ISSUE TITLE
Math Mode

### ISSUE THREAD

**Issue by CT075** [smlhelp/book#10]
mdbook is terrible at math mode.

I can import my shoddy math dollars script that I use on my personal stuff, but it'd be nicer to have a more robust solution.

**Comment by oldwomanjosiah** [comment]
There are a couple of libraries that are well tested including [mathjax](https://www.mathjax.org/)[^mathjaxGithub] and [KaTeX](https://katex.org/) [^katexGithub]. Both of them require either explicitly running for each rendered math blob when the page is loaded, or running during the book compilation though, so they may not be the best solution.

[^mathjaxGithub]: https://github.com/mathjax/MathJax-src
[^katexGithub]: https://github.com/KaTeX/KaTeX
